---------------------------------------------------
-- Generated by it.unicam.ids.doit.model.ddl.DDL --
-- at 2020-12-10T16:16:36.046007Z                --
---------------------------------------------------

    create table competenza (
       id integer generated by default as identity,
        primary key (id)
    );

    create table manager (
       id integer generated by default as identity,
        primary key (id)
    );

    create table membership (
       utente_id integer not null,
        soggetti_di_cui_membro_id integer not null,
        primary key (utente_id, soggetti_di_cui_membro_id)
    );

    create table progetto (
       id integer generated by default as identity,
        primary key (id)
    );

    create table proposta (
       id integer generated by default as identity,
        primary key (id)
    );

    create table soggetto_collettivo (
       id integer generated by default as identity,
        descrizione varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table utente (
       id integer generated by default as identity,
        password varchar(255),
        username varchar(255),
        email varchar(255),
        family_name varchar(255),
        given_name varchar(255),
        primary key (id)
    );

    alter table membership 
       add constraint FKfnqw89u5hst893oha0okttmb2 
       foreign key (soggetti_di_cui_membro_id) 
       references soggetto_collettivo;

    alter table membership 
       add constraint FKmm1aq11j4sa275ntf7eetj9k0 
       foreign key (utente_id) 
       references utente;
