---------------------------------------------------
-- Generated by it.unicam.ids.doit.model.ddl.DDL --
-- at 2020-12-13T20:57:15.687478Z                --
---------------------------------------------------

    create table competenza (
       id integer generated by default as identity,
        primary key (id)
    );

    create table manager (
       id integer generated by default as identity,
        primary key (id)
    );

    create table membership (
       utente_id integer not null,
        soggetto_collettivo_id integer not null,
        primary key (utente_id, soggetto_collettivo_id)
    );

    create table progetto (
       id integer generated by default as identity,
        descrizione varchar(255),
        titolo varchar(255),
        primary key (id)
    );

    create table proposta (
       id integer generated by default as identity,
        primary key (id)
    );

    create table soggetto_collettivo (
       id integer generated by default as identity,
        descrizione varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table utente (
       id integer generated by default as identity,
        password varchar(255),
        username varchar(255),
        email varchar(255),
        family_name varchar(255),
        given_name varchar(255),
        primary key (id)
    );

    alter table membership 
       add constraint FKs2mdi92irkvr7b7i6j4b0abbs 
       foreign key (soggetto_collettivo_id) 
       references soggetto_collettivo;

    alter table membership 
       add constraint FKmm1aq11j4sa275ntf7eetj9k0 
       foreign key (utente_id) 
       references utente;
