---------------------------------------------------
-- Generated by it.unicam.ids.doit.model.ddl.DDL --
-- at 2021-05-02T10:11:15.938629Z                --
---------------------------------------------------

    create table account (
       email varchar(255),
        username varchar(255),
        id integer not null,
        primary key (id)
    );

    create table appartenenza (
       id integer generated by default as identity,
        membro integer,
        organizzazione integer,
        primary key (id)
    );

    create table appartenenza_autorizzazioni (
       appartenenza_id integer not null,
        autorizzazioni varchar(255)
    );

    create table candidatura (
       id integer generated by default as identity,
        autopromozione varchar(255),
        inviata boolean not null,
        progetto_id integer,
        soggetto_id integer,
        primary key (id)
    );

    create table competenza (
       id integer generated by default as identity,
        tag varchar(255),
        primary key (id)
    );

    create table progetto (
       id integer generated by default as identity,
        descrizione clob,
        obiettivi clob,
        stato varchar(32),
        titolo varchar(255),
        owner_id integer not null,
        primary key (id)
    );

    create table progetto_competenza (
       progetto_id integer not null,
        competenzas_id integer not null,
        primary key (progetto_id, competenzas_id)
    );

    create table soggetto (
       discriminator_column char(31) not null,
        id integer generated by default as identity,
        primary key (id)
    );

    create table soggetto_collettivo (
       denominazione varchar(255),
        id integer not null,
        primary key (id)
    );

    create table soggetto_utente (
       cognome varchar(255),
        nome varchar(255),
        id integer not null,
        primary key (id)
    );

    alter table appartenenza 
       add constraint UKg5nooccab2b6fkxx5drwo4hbt unique (organizzazione, membro);

    alter table account 
       add constraint FKnqaiy90ei86hie9l7mcrk0715 
       foreign key (id) 
       references soggetto_utente;

    alter table appartenenza 
       add constraint FKi9e9ukfiqeuhthtxse07k0dnq 
       foreign key (membro) 
       references soggetto_utente;

    alter table appartenenza 
       add constraint FK2g1slostnx0hv8ml7ldcm3qv9 
       foreign key (organizzazione) 
       references soggetto_collettivo;

    alter table appartenenza_autorizzazioni 
       add constraint FKrids4e1dmrc9cau1yvqqube2c 
       foreign key (appartenenza_id) 
       references appartenenza;

    alter table candidatura 
       add constraint FKfwc09vi8rk6qfmtnethsyprtq 
       foreign key (progetto_id) 
       references progetto;

    alter table candidatura 
       add constraint FK60v7vlu62ns1phrmwu299l3dy 
       foreign key (soggetto_id) 
       references soggetto;

    alter table progetto 
       add constraint FKjt89cilf7e7by1bwj66nw5do7 
       foreign key (owner_id) 
       references soggetto_collettivo;

    alter table progetto_competenza 
       add constraint FKfbiihm6cw1wdhshp08aoqfa72 
       foreign key (competenzas_id) 
       references competenza;

    alter table progetto_competenza 
       add constraint FKcbg5prufeotnniutpt3tl84qx 
       foreign key (progetto_id) 
       references progetto;

    alter table soggetto_collettivo 
       add constraint FKcua854gf08awjbpo8firrkcp0 
       foreign key (id) 
       references soggetto;

    alter table soggetto_utente 
       add constraint FKr4ac3d3ofiycub3d0614ftvq4 
       foreign key (id) 
       references soggetto;
